#!/usr/bin/env python3
"""gen_confusions -- rebuild mrz_confusions.py from raw v6 reads.

The checksum repair picks among several edits that satisfy Mod-10; on
fields whose weight phase aligns with the composite check (passport_no,
personal_no) coincidental edits can verify just as well as the true one.
Ranking by an empirical (GT char, OCR char) prior fixes that.

This tool runs the raw PP-OCRv6 pipeline (no TTA, no slot pass, no
repair) over a slice of the *training* corpus, counts position-wise
pairs where GT and prediction have equal length, and writes the static
table mrz_confusions.py. Evaluation corpora are never used here.

    /tmp/paddle_venv/bin/python 6_1_PaddleOCR/gen_confusions.py \
        [--corpus PATH] [--stride 5] [--out PATH]
"""
from __future__ import annotations
import argparse
import json
from collections import Counter
from pathlib import Path

import numpy as np
from PIL import Image

import paddle_v6

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CORPUS = ROOT / "6_mrz_ocr" / "data" / "corpus_train" / "corpus.json"
DEFAULT_OUT = Path(__file__).resolve().parent / "mrz_confusions.py"


def _pairs(gt: str, pred: str) -> Counter:
    if len(gt) != len(pred):
        return Counter()
    return Counter(g + p for g, p in zip(gt, pred))


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--corpus", default=str(DEFAULT_CORPUS))
    ap.add_argument("--stride", type=int, default=5)
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    ap.add_argument("--scale", type=int, default=3)
    args = ap.parse_args()

    corpus = Path(args.corpus)
    recs = json.loads(corpus.read_text())["records"]
    rec, mode = paddle_v6._get_rec()
    if rec is None:
        raise SystemExit("paddlex/onnxruntime unavailable (mode=%s)" % mode)

    counts = Counter()
    n_used = 0
    for i, r in enumerate(recs):
        if args.stride > 1 and i % args.stride:
            continue
        img = corpus.parent / r["image"]
        if not img.exists():
            continue
        gray = np.asarray(Image.open(img).convert("L"))
        y0, y1 = paddle_v6._find_mrz_band(gray)
        row1, row2 = paddle_v6._split_rows(gray, y0, y1)
        for gt, row in ((r["line1"], row1), (r["line2"], row2)):
            txt, _score, _ = paddle_v6._rec_row(rec, row, args.scale)
            counts += _pairs(gt, paddle_v6._filter(txt))
        n_used += 1

    out = Path(args.out)
    lines = [
        '"""mrz_confusions -- empirical (GT char, OCR char) counts.',
        "",
        "Generated by gen_confusions.py from raw PP-OCRv6 reads of the",
        f"training corpus (n={n_used} images, stride={args.stride}, scale="
        f"{args.scale}x, no TTA/slot/repair). Keys are GT+OCR char pairs.",
        "Do not hand-edit; rerun the generator instead.",
        '"""',
        "",
        "COUNTS = {",
    ]
    for k, v in sorted(counts.items(), key=lambda kv: (-kv[1], kv[0])):
        lines.append(f"    {k!r}: {v},")
    lines += [
        "}",
        "",
        "",
        "def prior(gt: str, ocr: str) -> float:",
        '    """Smoothed count of `ocr` having been read where GT was `gt`."""',
        "    return 1.0 + COUNTS.get(gt + ocr, 0)",
        "",
    ]
    out.write_text("\n".join(lines))
    top = ", ".join(f"{k}:{v}" for k, v in counts.most_common(12))
    print(f"wrote {out} ({len(counts)} pairs, {n_used} images)")
    print(f"top: {top}")


if __name__ == "__main__":
    main()
